### ISSUE TITLE
Bug in vatsatseg new version?

### ISSUE THREAD

**Issue by lelamuc** [maxdiefenbach/vatsatseg#1]
![bild1](https://user-images.githubusercontent.com/42834218/50688081-2b219900-1024-11e9-8df8-e08439c08ff7.jpg)
When using the new version of vatsatseg, somehow the python script I used before does not work any more. It gives me the correct output, but the output .nii files do not appear in the directory or in the "real" folder. Did the commands for the python notebook change with the new version?

**Comment by lelamuc** [comment]
I looked at the issue with Sophia today and we could not find the reason for the output not appearing in the respective folder.
However we opened the vatsatseg with the Kommandozentrale and the following appeared:

> D:\Dokumente\_Forschung\Studie- PLIS\PLIS Daten\vatsatsegPLIS>vatsatseg -w IM_00
> 13_PLIS049BC_4_mDIX_SequenceNumber_702_W.dcm -f IM_0013_PLIS049BC_4_mDIX_Sequenc
> eNumber_702_F.dcm -o IM_0013_PLIS049BC_4_mDIX_SequenceNumber_702_labelmap.nii.gz
> 
> INFO:vatsatseg.vatsatseg:Read input. ...
> INFO:vatsatseg.vatsatseg:Done.
> INFO:vatsatseg.vatsatseg:Read labeldescfile. ...
> INFO:vatsatseg.vatsatseg:Done.
> INFO:vatsatseg.vatsatseg:Start segmentation. ...
> d:\programme\python\lib\site-packages\skimage\morphology\convex_hull.py:61: Runt
> imeWarning: Mean of empty slice.
>   offset = coords.mean(axis=0)
> d:\programme\python\lib\site-packages\numpy\core\_methods.py:73: RuntimeWarning:
>  invalid value encountered in true_divide
>   ret, rcount, out=ret, casting='unsafe', subok=False)
> Traceback (most recent call last):
>   File "d:\programme\python\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "d:\programme\python\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "D:\Programme\Python\Scripts\vatsatseg.exe\__main__.py", line 9, in <module>
>   File "d:\programme\python\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "d:\programme\python\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "d:\programme\python\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "d:\programme\python\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "d:\programme\python\lib\site-packages\vatsatseg\vatsatseg.py", line 48,
> in cli
>     vatsatseg(water, fat, output)
>   File "d:\programme\python\lib\site-packages\vatsatseg\vatsatseg.py", line 123,
>  in vatsatseg
>     labelmap = vatsatseg_3d(w_img, f_img, labeldict)
>   File "d:\programme\python\lib\site-packages\vatsatseg\vatsatseg.py", line 175,
>  in vatsatseg_3d
>     labeldict)
>   File "d:\programme\python\lib\site-packages\vatsatseg\vatsatseg.py", line 207,
>  in get_labelmap_2d
>     vat_mask = get_vat_mask(f_mask, abdominal_water_mask)
>   File "d:\programme\python\lib\site-packages\vatsatseg\vatsatseg.py", line 368,
>  in get_vat_mask
>     vat_mask = convex_hull_image(binary_opening(vat_mask)) & f_mask
>   File "d:\programme\python\lib\site-packages\skimage\morphology\convex_hull.py"
> , line 65, in convex_hull_image
>     chull = Delaunay(coords).convex_hull
>   File "qhull.pyx", line 1826, in scipy.spatial.qhull.Delaunay.__init__
>   File "qhull.pyx", line 275, in scipy.spatial.qhull._Qhull.__init__
> ValueError: No points given

Maybe this helps with finding the error?

**Comment by maxdiefenbach** [comment]
I have an idea on what happens. I'll try to fix it this week.

**Comment by maxdiefenbach** [comment]
@lelamuc Where do I find the same dataset on the NAS?
